# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Update README.md

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 */1 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: yarn install
    - run: yarn start
      env:
        TWITCH_CLIENT_ID: ${{ secrets.TWITCH_CLIENT_ID }}
        TWITCH_CLIENT_SECRET: ${{ secrets.TWITCH_CLIENT_SECRET }}
        TWITCH_USER_ID: ${{ secrets.TWITCH_USER_ID }}
    - run: |
        git config user.name SantiMA10
        git config user.email santiagomartinagra@gmail.com
        git add README.md
        git diff --quiet && git diff --staged --quiet || git commit -m "[bot] docs(README.md): Update with latest info"
        git push origin master